name: geocoder_pro_example
description: A modern Flutter example demonstrating Google Maps & OpenStreetMap Geocoding and spatial utilities with geocoder_pro.
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: ^3.7.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geocoder_pro:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true